### ISSUE TITLE
Sample doesn't work with keyring provider

### ISSUE THREAD

**Issue by jbregman** [conjurinc/summon-keyring#1]
summon -p keyring.py --yaml 'MYSECRET: !var secret/path' printenv MYSECRET  

results in the following error:

Error fetching variable MYSECRET: Traceback (most recent call last):
  File "/usr/local/lib/summon/keyring.py", line 22, in <module>
    value = keyring.get_password(
AttributeError: 'module' object has no attribute 'get_password'

If I run "python -m keyring get summon secret/path", then the value is correct.

This is with summon 0.4.0 - and it appears on both Mac OSX, and Ubuntu 14.0.4

**Comment by infamousjoeg** [comment]
This issue can be closed, @jvanderhoof.  I successfully tested it on MacOS X and was able to pull back a value:

```shell
$ summon -p keyring.py --yaml 'TEST: !var aws/access_key_id' printenv TEST
AKIA[redacted]```
