### ISSUE TITLE
Old respositories in docs

### ISSUE THREAD

**Issue by hertus** [conjurinc/summon-keyring#15]
## Summary
Old repositories and URL in README.MD and summon docs as well

## Steps to Reproduce
- [x] See [https://github.com/cyberark/summon-keyring/blob/master/README.md](url) where  **git@github.com:conjurinc/summon-keyring.git**  is mentioned.
- [x] Also see [https://cyberark.github.io/summon/docker.html](url) where **https://github.com/conjurdemos/summon-docker-tutorial.git** is mentioned which does not exist anymore

## Expected Results
Repository and links that actually exist

**Comment by izgeri** [comment]
Thanks for flagging this for us @hertus - we'll take a look at cleaning up these docs shortly.

I expect the first issue just needs to be updated to point to `cyberark/summon-keyring`, which we can do. The second may take some digging to find the docker tutorial and make it available again :)

**Comment by izgeri** [comment]
See #16 for a fix for the first issue.

The second issue it looks like I already filed an issue for a while ago 😅 that can be found here: https://github.com/cyberark/summon/issues/112

**Comment by izgeri** [comment]
@hertus we updated the [Docker tutorial](https://cyberark.github.io/summon/docker.html) (finally 😬) to ensure all of the content is available. I hope you will try working through it again! Please file an issue in https://github.com/cyberark/summon if you run into any additional issues. Thanks again for helping us improve our documentation!!
